### ISSUE TITLE
Generate keypair from bitcoin key

### ISSUE THREAD

**Issue by sertony** [Jaxx-io/openpgpjs-secp256k1#2]
Can anybody explain how **material** options field works or should work?

I can't see any details in source code as well as I don't notice that the presence of this **material** key changes anything at all. As for me it just creates a new pair every time I call generateKey function.

Thank you.

**Comment by ismaelbej** [comment]
The master in this repo is an old copy without the 'material' bits. A more recent copy with material bits is at our pull request branch https://github.com/Jaxx-io/openpgpjs/tree/issue/427 that we send upstream to merge, but is almost 1 year old now.

Upstream has create a branch for merging at https://github.com/openpgpjs/openpgpjs/tree/ecc_nist, but they have removed the 'material' bits. But it should not be difficult to add again from the original commit https://github.com/Jaxx-io/openpgpjs/commit/6a4d639145a95deac8f065757ed8649caa60d9e2. 

Hope this helps.

**Comment by sertony** [comment]
Thank you @ismaelbej!
